language: node_js
node_js: '7'
script: true
deploy:
  provider: npm
  email: Serban.Petrescu@outlook.com
  api_key:
    secure: rX36ysZDvndBV7wdD4COle0Jycppk06ncYzHRIEy//AYjy4a4JT3tgj3/gVefaySE6PYsJBzxsgkZRx7j9qJUhNCsCz3UhwF8OSBloDDik9XE4iyR9g2iFeQY9LQTbdsNanoXGukgVbRiCuUQ/K51snZe6fQwS5hSy3Q8AE93Re5Sqs6xCZwW0N2LxMLynAKMu+r8ZPh+hAXRK4wsk1ftCEeq8CP9R6lrmd0EmsYanTaEd9N7XjinXAlZvSFsDWACFOfNJudQRAoRd3D8KmqIdzf1xpkFI/8thi5sNkWqhBjSvSXWvjOGnTIJOixK5FeW02nOkRuUhIkatbc7jy4OmXfvfiu+K1FxM2iKrYXdNKV2T0MAZbJZmv+igdMAHnsBs6Q3jduamTpPYwCkZ4jMMt/yZLyFIMCA2n1F/vRKrBne4LezPS5iE6KH9pZSFj4mATR91aSIpeJgAltHYlXq7zbMrOqJTlQ0zdv0ZI3RImeMvKKS4721sp+LryjHasX3XKeyjgqs7Qohaq3XAW4uDWYBGnhcAF5z3L0YKSsQ89ODPP8NICB81rpV6wnCjbFx7lUI0cZtcY0t4thxfKXkKEL2ZCPtJoFn3LuBAq+WKAX8rfMr09NVHDe4JrVeVNqtC8vscfewacGnTncNDX0pCL655RzingUIpBAt+z+GDU=
  on:
    tags: true
